### PR TITLE
AI boss and spawning

### PR DESCRIPTION
**Pull request by joshuaemer**

### CODE REVIEW

**Comment by joshuaemer** [comment]
GitHub desktop let me merge without a pull request, I needed to resolve the conflicts on there since they were too complex to resolve on here. Most of the conflicts were for meta data except for a removed comment in SkeletonMovement.cs. I referenced the pull request #71  in the commit message though. I still need a review to avoid a protocol violation.

**Comment by mjholder** [comment]
Will not let me review for some reason but this is approved.

**Comment by mjholder** [comment]
Pull Request still says review required but I have reviewed and approved this.

**Comment by joshuaemer** [comment]
#61 #25

**Pull request merged**
